CREATE DATABASE COUNTRY;
USE COUNTRY;

CREATE TABLE CITIZEN(
    NATIONAL_ID INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,	
    AGE INT ,
    BIRTH_DATE DATE
);

DROP TABLE CITIZEN;
DROP TABLE CITIZEN cascade;

ALTER TABLE CITIZEN
ADD COLUMN FATHERS_NAME varchar(50);
ALTER TABLE CITIZEN
ADD COLUMN MOTHERS_NAME varchar(50);

ALTER TABLE CITIZEN
DROP COLUMN AGE;

ALTER TABLE CITIZEN RENAME TO CITIZEN_INFO;
ALTER TABLE CITIZEN_INFO RENAME TO CITIZEN;

ALTER TABLE CITIZEN
MODIFY COLUMN NAME VARCHAR(30);

ALTER TABLE CITIZEN
MODIFY COLUMN FATHERS_NAME VARCHAR(50)
AFTER NAME;

ALTER TABLE CITIZEN
MODIFY COLUMN MOTHERS_NAME VARCHAR(50)
AFTER FATHERS_NAME;

ALTER TABLE CITIZEN
MODIFY COLUMN NAME VARCHAR(30)
FIRST;

CREATE TABLE DEPARTMENT(
    DEPT_NAME varchar(20),
    TITLE varchar(30),
    EST_YEAR char(4),
    primary key(DEPT_NAME)
);

CREATE TABLE COURSE(
    COURSE_ID varchar(8),
    TITLE varchar(30),
    PROGRAM varchar(5),
    DEPT_NAME varchar(20),	
    primary key(COURSE_ID,PROGRAM),
    foreign key(DEPT_NAME) references DEPARTMENT(DEPT_NAME)
);

CREATE TABLE NEW_COURSE AS select * FROM COURSE;

ALTER TABLE COURSE
ADD COLUMN CREDIT int;

ALTER TABLE COURSE 
ADD constraint CHK_CREDIT CHECK(CREDIT>0.75);

ALTER TABLE COURSE
DROP constraint CHK_CREDIT;

ALTER TABLE COURSE 
ADD constraint unique (COURSE_ID) ;

ALTER TABLE COURSE
MODIFY COLUMN DEPT_NAME VARCHAR(20) NOT NULL;
