CREATE TABLE CITIZEN(
	NATIONAL_ID INT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  BIRTH_DATE DATE,
  FATHERS_NAME varchar(50),
  MOTHERS_NAME varchar(50)
);

INSERT INTO CITIZEN(NAME,NATIONAL_ID,FATHERS_NAME,MOTHERS_NAME,BIRTH_DATE)
VALUES("ARIYAN",24793,"EHSAN","NEHERIN","2003-08-10");

SELECT NATIONAL_ID
FROM CITIZEN;

SELECT NATIONAL_ID=1231
FROM CITIZEN;

SELECT NATIONAL_ID
FROM CITIZEN
WHERE NAME="ARIYAN" ;

SELECT NATIONAL_ID
FROM CITIZEN
WHERE AGE>21 AND SALARY>200 ;

SELECT NATIONAL_ID
FROM CITIZEN
WHERE AGE>21 OR SALARY>200 ;

SELECT NATIONAL_ID
FROM CITIZEN
WHERE AGE!=21  ;

UPDATE CITIZEN 
SET NAME="KHANDAKER ALI ARIYAN"
WHERE FATHERS_NAME="EHSAN";

DELETE FROM CITIZEN
WHERE NAME="KHANDAKER ALI ARIYAN";
