USE EMP;

CREATE VIEW TOTAL_SALARY AS 
SELECT NAME , CONCAT(SALARY,IFNULL(BONUS,0)) AS TOTAL_SALARY 
FROM EMPLOYEE;

CREATE VIEW PRESONAL_INFO AS
SELECT NAME,BIRTH_DATE 
FROM employee;

DROP VIEW total_salary;